package com.mobifone.model;
// Generated Jul 29, 2017 5:42:23 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GuarantyCashManage generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "GUARANTY_CASH_MANAGE", catalog = "mobifone_subsidy")
public class GuarantyCashManage implements java.io.Serializable {

	private Long id;
	private Long guarantorId;
	private Long guarantorOrgId;

	public GuarantyCashManage() {
	}

	public GuarantyCashManage(Long guarantorId, Long guarantorOrgId) {
		this.guarantorId = guarantorId;
		this.guarantorOrgId = guarantorOrgId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "guarantor_id")
	public Long getGuarantorId() {
		return this.guarantorId;
	}

	public void setGuarantorId(Long guarantorId) {
		this.guarantorId = guarantorId;
	}

	@Column(name = "guarantor_org_id")
	public Long getGuarantorOrgId() {
		return this.guarantorOrgId;
	}

	public void setGuarantorOrgId(Long guarantorOrgId) {
		this.guarantorOrgId = guarantorOrgId;
	}

}
