package com.mobifone.model;
// Generated Jul 29, 2017 5:42:23 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaction generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "TRANSACTION", catalog = "mobifone_subsidy")
public class Transaction implements java.io.Serializable {

	private Long id;
	private Double invoiceNumber;
	private String shopCode;
	private String guarantyCode;
	private String isdn;
	private String customerName;
	private Date customerBirthday;
	private String customerAddress;
	private String goodCode;
	private String goodName;
	private Date invoiceDate;
	private Double invoiceMoney;
	private Double guarantyMoney;
	private String postCode;

	public Transaction() {
	}

	public Transaction(Double invoiceNumber, String shopCode, String guarantyCode, String isdn, String customerName,
			Date customerBirthday, String customerAddress, String goodCode, String goodName, Date invoiceDate,
			Double invoiceMoney, Double guarantyMoney, String postCode) {
		this.invoiceNumber = invoiceNumber;
		this.shopCode = shopCode;
		this.guarantyCode = guarantyCode;
		this.isdn = isdn;
		this.customerName = customerName;
		this.customerBirthday = customerBirthday;
		this.customerAddress = customerAddress;
		this.goodCode = goodCode;
		this.goodName = goodName;
		this.invoiceDate = invoiceDate;
		this.invoiceMoney = invoiceMoney;
		this.guarantyMoney = guarantyMoney;
		this.postCode = postCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "invoice_number", precision = 22, scale = 0)
	public Double getInvoiceNumber() {
		return this.invoiceNumber;
	}

	public void setInvoiceNumber(Double invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	@Column(name = "shop_code", length = 125)
	public String getShopCode() {
		return this.shopCode;
	}

	public void setShopCode(String shopCode) {
		this.shopCode = shopCode;
	}

	@Column(name = "guaranty_code", length = 125)
	public String getGuarantyCode() {
		return this.guarantyCode;
	}

	public void setGuarantyCode(String guarantyCode) {
		this.guarantyCode = guarantyCode;
	}

	@Column(name = "isdn")
	public String getIsdn() {
		return this.isdn;
	}

	public void setIsdn(String isdn) {
		this.isdn = isdn;
	}

	@Column(name = "customer_name", length = 100)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "customer_birthday", length = 10)
	public Date getCustomerBirthday() {
		return this.customerBirthday;
	}

	public void setCustomerBirthday(Date customerBirthday) {
		this.customerBirthday = customerBirthday;
	}

	@Column(name = "customer_address", length = 100)
	public String getCustomerAddress() {
		return this.customerAddress;
	}

	public void setCustomerAddress(String customerAddress) {
		this.customerAddress = customerAddress;
	}

	@Column(name = "good_code", length = 45)
	public String getGoodCode() {
		return this.goodCode;
	}

	public void setGoodCode(String goodCode) {
		this.goodCode = goodCode;
	}

	@Column(name = "good_name", length = 100)
	public String getGoodName() {
		return this.goodName;
	}

	public void setGoodName(String goodName) {
		this.goodName = goodName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "invoice_date", length = 19)
	public Date getInvoiceDate() {
		return this.invoiceDate;
	}

	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	@Column(name = "invoice_money", precision = 22, scale = 0)
	public Double getInvoiceMoney() {
		return this.invoiceMoney;
	}

	public void setInvoiceMoney(Double invoiceMoney) {
		this.invoiceMoney = invoiceMoney;
	}

	@Column(name = "guaranty_money", precision = 22, scale = 0)
	public Double getGuarantyMoney() {
		return this.guarantyMoney;
	}

	public void setGuarantyMoney(Double guarantyMoney) {
		this.guarantyMoney = guarantyMoney;
	}

	@Column(name = "post_code", length = 45)
	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

}
